server:
  port: 8100
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
management:
  server:
    port: 9000
  endpoints:
    web:
      exposure:
        include: "*"
    shutdown:
      enabled: true
spring:
  boot:
    admin:
      url: http://localhost:9090/